// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<main.ConnectResult>;

export function Disconnect():Promise<main.ConnectResult>;

export function GetStatus():Promise<main.StatusResult>;
